apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.repository }}-{{ .Values.image.tag }}
spec:
  selector:
    app: {{ .Values.image.repository }}-{{ .Values.image.tag }}
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer
